/* 
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 * Author:  Mussa
 * Created: Mar 11, 2016
 */


DROP TABLE Mussa.InterestedEvents IF EXISTS;
DROP TABLE Mussa.Event IF EXISTS;
DROP TABLE Mussa.User IF EXISTS;
DROP SCHEMA Mussa if EXISTS;

CREATE SCHEMA Mussa AUTHORIZATION dba


CREATE TABLE  Mussa.User (
   id bigint GENERATED BY DEFAULT AS IDENTITY (START WITH 1) PRIMARY KEY,
   name varchar(100) NOT NULL,
   email varchar(100) NOT NULL,
   password varchar(100) NOT NULL
 );
GRANT SELECT ON Mussa.User TO PUBLIC ;

CREATE TABLE  Mussa.Event (
   id bigint GENERATED BY DEFAULT AS IDENTITY (START WITH 1) PRIMARY KEY,
   title varchar(100) NOT NULL,
   description varchar(500) NOT NULL,
   location varchar(100) NOT NULL,
   eventTime TIMESTAMP NOT NULL,
   createdBy int NOT NULL,
   FOREIGN KEY (createdBy) REFERENCES User(id)
 );
GRANT SELECT ON Mussa.Event TO PUBLIC;

CREATE TABLE  Mussa.InterestedEvents (
   userId bigint NOT NULL,   
   eventId bigint NOT NULL,   
   PRIMARY KEY (userId,eventId),
   FOREIGN KEY (userId) REFERENCES Mussa.User(id),
   FOREIGN KEY (eventId) REFERENCES Mussa.Event(id)
 );

GRANT SELECT ON Mussa.InterestedEvents TO PUBLIC ;

