
CREATE TABLE  User (id bigint GENERATED BY DEFAULT AS IDENTITY (START WITH 1) PRIMARY KEY,name varchar(100) NOT NULL,email varchar(100) NOT NULL,password varchar(100) NOT NULL);
GRANT SELECT ON User TO PUBLIC ;

CREATE TABLE  Event (id bigint GENERATED BY DEFAULT AS IDENTITY (START WITH 1) PRIMARY KEY,title varchar(100) NOT NULL,description varchar(500) NOT NULL,location varchar(100) NOT NULL,eventTime TIMESTAMP NOT NULL,createdBy int NOT NULL,FOREIGN KEY (createdBy) REFERENCES User(id));
GRANT SELECT ON Event TO PUBLIC;

CREATE TABLE  InterestedEvents (userId bigint NOT NULL,eventId bigint NOT NULL,PRIMARY KEY (userId,eventId),FOREIGN KEY (userId) REFERENCES User(id),FOREIGN KEY (eventId) REFERENCES Event(id));

GRANT SELECT ON InterestedEvents TO PUBLIC ;

